name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - name: my-step
        run: echo "Hello World!"
      - run: node --version
      - run: npm --version
